### ISSUE TITLE
The dwg file is too large and cannot be converted

### ISSUE THREAD

**Issue by toppemonkey** [aspose-cad/Aspose.CAD-for-Java#6]
**The dwg file is too large and an error is reported when outputting the pdf file：**

java.lang.RuntimeException: Error during PDF export: Specified argument was out of the range of valid values.
Parameter name: Parameter name: index
	at com.aspose.cad.internal.fx.a.b(Unknown Source)
	at com.aspose.cad.internal.fx.c.b(Unknown Source)
	at com.aspose.cad.internal.eS.a.a(Unknown Source)
	at com.aspose.cad.internal.eS.a.export(Unknown Source)
	at com.aspose.cad.z.a(Unknown Source)
	at com.aspose.cad.internal.b.e.invoke(Unknown Source)
	at com.aspose.cad.system.Threading.j.invoke(Unknown Source)
	at com.aspose.cad.system.Threading.n.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
Caused by: class com.aspose.cad.internal.Exceptions.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

Can you help me see it

**Comment by OleksiiGor** [comment]
Hello, we need to reproduce and inspect this file, you may attach it on our forums: https://forum.aspose.com/c/cad/19.
