### ISSUE TITLE
The dwg file is too large and cannot be converted svg/png

### ISSUE THREAD

**Issue by kangyaos** [aspose-cad/Aspose.CAD-for-Java#9]
class com.aspose.cad.internal.Exceptions.InvalidOperationException: Java heap space
com.aspose.cad.internal.b.d.a(Unknown Source)
com.aspose.cad.Image.a(Unknown Source)
com.aspose.cad.Image.saveInternal_internalized(Unknown Source)
com.aspose.cad.Image.save(Unknown Source)
com.sxhalo.fsms.util.CADFileUtil.dwgToPng(CADFileUtil.java:75)
com.sxhalo.fsms.util.CADFileUtil.main(CADFileUtil.java:129)
	at com.aspose.cad.internal.b.d.a(Unknown Source)
	at com.aspose.cad.Image.a(Unknown Source)
	at com.aspose.cad.Image.saveInternal_internalized(Unknown Source)
	at com.aspose.cad.Image.save(Unknown Source)
	at com.sxhalo.fsms.util.CADFileUtil.dwgToPng(CADFileUtil.java:75)
	at com.sxhalo.fsms.util.CADFileUtil.main(CADFileUtil.java:129)
Exception in thread "main" class com.aspose.cad.cadexceptions.ImageSaveException: Image saving failed. ---> class com.aspose.cad.cadexceptions.ImageSaveException: Image export failed. Java heap space ---> class com.aspose.cad.internal.Exceptions.InvalidOperationException: Java heap space
com.aspose.cad.internal.b.d.a(Unknown Source)
com.aspose.cad.Image.a(Unknown Source)
com.aspose.cad.Image.saveInternal_internalized(Unknown Source)
com.aspose.cad.Image.save(Unknown Source)
com.sxhalo.fsms.util.CADFileUtil.dwgToPng(CADFileUtil.java:75)
com.sxhalo.fsms.util.CADFileUtil.main(CADFileUtil.java:129)
   --- End of inner exception stack trace ---
com.aspose.cad.Image.a(Unknown Source)
com.aspose.cad.Image.saveInternal_internalized(Unknown Source)
com.aspose.cad.Image.save(Unknown Source)
com.sxhalo.fsms.util.CADFileUtil.dwgToPng(CADFileUtil.java:75)
com.sxhalo.fsms.util.CADFileUtil.main(CADFileUtil.java:129)
   --- End of inner exception stack trace ---
com.aspose.cad.Image.saveInternal_internalized(Unknown Source)
com.aspose.cad.Image.save(Unknown Source)

Please help me see

**Comment by OleksiiGor** [comment]
Hello, we need to test your file on our side, you may attach it on our forums: https://forum.aspose.com/c/cad/19.
